config/routes.rb
Livetrial::Application.routes.draw do
  resources :cloud_accounts

  resources :trials
  resources :users
  resources :sessions

  match 'logout', :to => 'sessions#destroy'

end

app/models/cloud_account.rb
class CloudAccount < ActiveRecord::Base
end

app/controllers/cloud_accounts_controller.rb
class CloudAccountsController < ApplicationController

  before_filter :require_login, :session_expiry
  # GET /cloud_accounts
  # GET /cloud_accounts.json
  def index
    @cloud_accounts = CloudAccount.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render :json => @cloud_accounts }
    end
  end

  # GET /cloud_accounts/1
  # GET /cloud_accounts/1.json
  def show
    @cloud_account = CloudAccount.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render :json => @cloud_account }
    end
  end

  # GET /cloud_accounts/new
  # GET /cloud_accounts/new.json
  def new
    @cloud_account = CloudAccount.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render :json => @cloud_account }
    end
  end

  # GET /cloud_accounts/1/edit
  def edit
    @cloud_account = CloudAccount.find(params[:id])
  end

  # POST /cloud_accounts
  # POST /cloud_accounts.json
  def create
    @cloud_account = CloudAccount.new(params[:cloud_account])

    respond_to do |format|
      if @cloud_account.save
        format.html { redirect_to @cloud_account, :notice => 'Cloud account was successfully created.' }
        format.json { render :json => @cloud_account, :status => :created, :location => @cloud_account }
      else
        format.html { render :action => "new" }
        format.json { render :json => @cloud_account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /cloud_accounts/1
  # PUT /cloud_accounts/1.json
  def update
    @cloud_account = CloudAccount.find(params[:id])

    respond_to do |format|
      if @cloud_account.update_attributes(params[:cloud_account])
        format.html { redirect_to @cloud_account, :notice => 'Cloud account was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render :action => "edit" }
        format.json { render :json => @cloud_account.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /cloud_accounts/1
  # DELETE /cloud_accounts/1.json
  def destroy
    @cloud_account = CloudAccount.find(params[:id])
    @cloud_account.destroy

    respond_to do |format|
      format.html { redirect_to cloud_accounts_url }
      format.json { head :ok }
    end
  end
end

app/helpers/cloud_accounts_helper.rb
module CloudAccountsHelper
end

app/views/cloud_accounts/_form.html.erb
<%= form_for(@cloud_account) do |f| %>
  <% if @cloud_account.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cloud_account.errors.count, "error") %> prohibited this cloud_account from being saved:</h2>

      <ul>
      <% @cloud_account.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :provider %><br />
    <%= f.text_field :provider %>
  </div>
  <div class="field">
    <%= f.label :username %><br />
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :apikey %><br />
    <%= f.text_field :apikey %>
  </div>
  <div class="field">
    <%= f.label :privatekey %><br />
    <%= f.text_field :privatekey %>
  </div>
  <div class="field">
    <%= f.label :certificate %><br />
    <%= f.text_field :certificate %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cloud_accounts/edit.html.erb
<img src="http://www.snaplogic.com/images/common/logo.png">
<br>
Current User is: <%= current_user.username %> <%= link_to 'Logout', logout_path %>
<br><br>

<h1>Editing Cloud Account</h1>

<%= render 'form' %>

<%= link_to 'Show', @cloud_account %> |
<%= link_to 'Back', cloud_accounts_path %>

app/views/cloud_accounts/index.html.erb
<img src="http://www.snaplogic.com/images/common/logo.png">
<br>
Current User is: <%= current_user.username %> <%= link_to 'Logout', logout_path %>
<br><br>

<h1>Listing Cloud Accounts</h1>


<table border=+1>
  <tr>
    <th>Provider</th>
    <th>Username</th>
    <th>Apikey</th>
    <th>Privatekey</th>
    <th>Certificate</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @cloud_accounts.each do |cloud_account| %>
  <tr>
    <td><%= cloud_account.provider %></td>
    <td><%= cloud_account.username %></td>
    <td><%= cloud_account.apikey %></td>
    <td><%= cloud_account.privatekey %></td>
    <td><%= cloud_account.certificate %></td>
    <td><%= link_to 'Show', cloud_account %></td>
    <td><%= link_to 'Edit', edit_cloud_account_path(cloud_account) %></td>
    <td><%= link_to 'Destroy', cloud_account, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Cloud account', new_cloud_account_path %>

app/views/cloud_accounts/new.html.erb
<img src="http://www.snaplogic.com/images/common/logo.png">
<br>
Current User is: <%= current_user.username %> <%= link_to 'Logout', logout_path %>
<br><br>
<h1>New Cloud Account</h1>

<%= render 'form' %>

<%= link_to 'Back', cloud_accounts_path %>

app/views/cloud_accounts/show.html.erb
<img src="http://www.snaplogic.com/images/common/logo.png">
<br>
Current User is: <%= current_user.username %> <%= link_to 'Logout', logout_path %>
<br><br>

<p id="notice"><%= notice %></p>

<p>
  <b>Provider:</b>
  <%= @cloud_account.provider %>
</p>

<p>
  <b>Username:</b>
  <%= @cloud_account.username %>
</p>

<p>
  <b>Apikey:</b>
  <%= @cloud_account.apikey %>
</p>

<p>
  <b>Privatekey:</b>
  <%= @cloud_account.privatekey %>
</p>

<p>
  <b>Certificate:</b>
  <%= @cloud_account.certificate %>
</p>


<%= link_to 'Edit', edit_cloud_account_path(@cloud_account) %> |
<%= link_to 'Back', cloud_accounts_path %>