config/routes.rb
Livetrial::Application.routes.draw do
  resources :cloud_accounts

  resources :trials
  resources :users
  resources :sessions

  match 'logout', :to => 'sessions#destroy'

end

app/models/trial.rb
#---
# Excerpted from "Advanced Rails Recipes",
# published by The Pragmatic Bookshelf.
# Copyrights apply to this code. It may not be used to create training material, 
# courses, books, articles, and the like. Contact us if you are in doubt.
# We make no guarantees that this code is fit for any purpose. 
# Visit http://www.pragmaticprogrammer.com/titles/fr_arr for more book information.
#---

require 'resolv'

class Trial < ActiveRecord::Base
  
  EMAIL_PATTERN = /(\S+)@(\S+)/

  validates_format_of :customeremail, :with => EMAIL_PATTERN
  validates_uniqueness_of :customeremail
  
  def validate
    unless errors[:customeremail].count >= 1
    #unless errors.on(:customeremail)
      unless valid_domain?(customeremail)
        errors.add(:customeremail, 'domain name appears to be incorrect') 
      end
    end
  end


  SERVER_TIMEOUT = 3 # seconds

  def valid_domain?(email)
    domain = email.match(EMAIL_PATTERN)[2]
    
    dns = Resolv::DNS.new

    Timeout::timeout(SERVER_TIMEOUT) do
      # Check the MX records
      mx_records = 
        dns.getresources(domain, Resolv::DNS::Resource::IN::MX)
    
      mx_records.sort_by {|mx| mx.preference}.each do |mx|
        a_records = dns.getresources(mx.exchange.to_s, 
                                     Resolv::DNS::Resource::IN::A)
        return true if a_records.any?
      end
      
      # Try a straight A record
      a_records = dns.getresources(domain, Resolv::DNS::Resource::IN::A)
      a_records.any?
    end
  rescue Timeout::Error, Errno::ECONNREFUSED
    false
  end

  # Check if the trials has expired
  def expired?
    created_at < 14.days.ago && updated_at < 14.days.ago
  end

  # Check if the trial has reached the point of deletion threshold
  def threshold?
    created_at < 200.days.ago && updated_at < 200.days.ago
  end

  # Extend the livetrial by 14 days
  def extendbyfourteendays
    updated_at = Time.now
  end

  # Extend the livetrial by 30 days
  def extendbythirthydays
    update_at = update_at + 14.days.from_now
  end

  # This function gets the trialpw from the instance
  def sftptrialpwget( host, username, password )
    require 'net/ssh'
    require 'net/http'
    require 'net/sftp'

    @trialpw = nil
    uri = URI.parse("http://#{host}")

    begin
      # Check if the server is up first for four minutes
      # Using HTTP
      Timeout::timeout(240) do
        begin
          while ( Net::HTTP.get_response(uri).code != "200" ) do
            sleep 2
          end
        rescue Errno::ECONNREFUSED
          # Connection refused means the server is coming up
          # But the SnapLogic server is not up yet
          retry
        end
      end

      Net::SFTP.start(host, username, :password => password) do |sftp|
        begin
          @data = sftp.download!("/opt/snaplogic/config/textpasswords").split('\n')
        rescue RuntimeError
          # File not found maybe a earlier version of snaplogic
          @data = nil
          @trialpw = 'thinkcloud'
        end

        @data.each do |entry|
          entry = entry.split(' ')
          if (entry.first == "admin:")
             @trialpw = entry.second
             break
          end
        end
      end

    rescue Timeout::Error
      # This means that the server didn't come up, timeout
      raise
    rescue Net::SSH::AuthenticationFailed
      # Do nothing "Authentication failed"
    rescue SocketError
      # Do nothing the hostname is bogus
    end # end of rescue
    @trialpw
  end

  def check_provision_status( host, username, password)
    require 'net/ssh'
    require 'net/http'
    require 'net/sftp'

    uri = URI.parse("http://#{host}/__snap__/__static__/protected/ground.cert")

    begin
      # Using HTTP
      Timeout::timeout(240) do
        begin
          if ( Net::HTTP.get_response(uri).code == "404" ) then
            status = "Provisioned"
          elsif ( Net::HTTP.get_response(uri).code == "200" ) then
            status = "Not provisioned"
          else
            status = "Unknown"
          end
        rescue Errno::ECONNREFUSED
          puts "Exception"
          # Connection refused means the server is coming up
          # But the SnapLogic server is not up yet
        end
      end

    rescue Timeout::Error
      # This means that the server is not up, timeout
       status = "Down"
    end # End of rescue
    status
  end

  def check_provision_return_code( host, username, password)
    require 'net/ssh'
    require 'net/http'
    require 'net/sftp'

    @uri = URI.parse("http://#{host}/__snap__/__static__/protected/ground.cert")

    @request = Net::HTTP::Get.new(@uri.request_uri)
    @request.basic_auth username, password

    begin
      @response = Net::HTTP.start(@uri.host, @uri.port) {|http|
        http.request(@request)
      }
      @response.code
    rescue SocketError => e
      puts "Exception: " + e
    rescue
      puts "General exception"
    end

  end

end

app/controllers/trials_controller.rb
class TrialsController < ApplicationController
  # Include the snaplogic rackspace library 

  before_filter :require_login, :session_expiry

  # GET /trials
  # GET /trials.xml
  def index
    #@trials = Trial.all
    if  params[:customername].nil? and params[:customeremail]
       @trials = Trial.find(:all, :conditions => ["customeremail = ?", params[:customeremail]])
    elsif params[:customername] and params[:customeremail].nil?
       @trials = Trial.find(:all, :conditions => ["customername = ?", params[:customername]])
    elsif params[:customername] and params[:customeremail]
       @trials = Trial.find(:all, :conditions => ["customername = ? AND customeremail = ?",
       params[:customername], params[:customeremail]])
    else
       @trials = Trial.paginate(:page => params[:page], :per_page => 20)
       #@trials = Trial.all
    end

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @trials }
      format.json  { render :json => @trials }
    end
  end

  # GET /trials/1
  # GET /trials/1.xml
  def show
    @trial = Trial.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @trial }
      format.json  { render :json => @trial }
    end
  end

  # GET /trials/customeremail
  # GET /trials/customeremail.xml
  def shownew
    @trial = Trial.find_by_customeremail(params[:id])

    respond_to do |format|
      format.html # show_name.html.erb
      format.xml { render :xml => @trial }
      format.json { render :json => @trial }
    end
  end


  # GET /trials/new
  # GET /trials/new.xml
  def new
    @trial = Trial.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @trial }
      format.json  { render :json => @trial }
    end
  end

  # GET /trials/1/edit
  def edit
    @trial = Trial.find(params[:id])
  end

  # POST /trials.xml
  # POST /trials.json
  def create
    @trial = Trial.new(params[:trial])

    @cloud_accounts = CloudAccount.all

    # Get rid of non rackspace accounts (AWS, gogrid, etc)
    @cloud_accounts.each_with_index do |e, i|
      @cloud_accounts.delete_at(i) if (e.provider.casecmp("Rackspace") != 0)
    end
    # Pick a ramdom Rackspace Account
    current_cloud_account = @cloud_accounts[rand(@cloud_accounts.count)]

    # Assign username and apikey
    username = current_cloud_account.username
    apikey = current_cloud_account.apikey

    respond_to do |format|
      if @trial.save
        parameters = ["-u",username,"-a",apikey,
                      "-C",@trial.customername,"-E",@trial.customeremail,
                      "-i", "16631193", "-F", "3"]
        options = SnaplogicRackspace::ParseArguments.parse(parameters)
        @livetrial = SnaplogicRackspace::LiveTrialServer.new(options)
        puts options
        # Create live trial server
        @livetrial.createlive(options)
        server = @livetrial.newserver
        # Populate live trial instance parameters
        @trial.instancepw = server.adminPass
        @trial.instanceid = server.id
        @trial.instancename = server.name
        @trial.imageflavor = server.flavor.id
        @trial.imageid = server.imageId
        @trial.cloudaccount = username

        # Get the server public ip
        @trial.publicipaddr = server.addresses[:public].first

        # Save the parameters above returned by rackspace
        # This is so that we delete instances cleanly
        # in case something fails
        @trial.save

        # Sleep for a 240 seconds for livetrial to come up
        sleep(240)

        # Get the password for the snaplogic server
        @trial.trialpw = @trial.sftptrialpwget(server.name, 'root', server.adminPass)
        # If password is nil then return error
        # Server didn't come up or something wrong
        if @trial.trialpw.nil?
          format.html { render :action => "new" }
          format.xml  { render :xml => @trial.errors, :status => :unprocessable_entity }
          format.json  { render :json => @trial.errors, :status => :unprocessable_entity }
        end

        # Start the provisioning by making ReST call to jenkins
        status = "Not provisioned"
        RestClient.post('https://dummy:Snaplogic123!@50.56.216.101/job/SnapLogic%20Sidekick%20Build%20Provisioner/buildWithParameters', :SVN_ID => '-i 18328', :BRANCH => '-b 3.3.1', :CLOUDSERVER => "-c #{@trial.instancename}", :CUSTOMERNAME => "-n \"#{@trial.customername}\"") \
        {|response, request, result, &block|
          case response.code
            when 200
              status = "Provisioning"
            # response
            when 302
              status = "Provisioning"
            # response
            # else
            #   response.return!(request, result, &block)
            end
        }

        @trial.status = status

        # Wait for 10 minutes
        # sleep(500)

        # Send email to the customer specifying that their livetrial is completed
        # begin
        #   Notifier.welcome(@trial).deliver
        # rescue Errno::ECONNREFUSED => e
        #   # Catch the case where there's no sendmail in the box
        #   logger.info "Caught exception when trying to send email" + e
        # end

        # Save the parameters above returned by rackspace
        unless @trial.save
          format.html { render :action => "new" }
          format.xml  { render :xml => @trial.errors, :status => :unprocessable_entity }
          format.json  { render :json => @trial.errors, :status => :unprocessable_entity }
        end

        format.html { redirect_to(@trial, :notice => 'Trial was successfully created.') }
        format.xml  { render :xml => @trial, :status => :created, :location => @trial }
        format.json  { render :json => @trial, :status => :created, :location => @trial }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @trial.errors, :status => :unprocessable_entity }
        format.json  { render :json => @trial.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /trials/1
  # PUT /trials/1.xml
  # PUT /trials/1.json
  def update
    @trial = Trial.find(params[:id])

    respond_to do |format|
      if @trial.update_attributes(params[:trial])
        format.html { redirect_to(@trial, :notice => 'Trial was successfully updated.') }
        format.xml  { head :ok }
        format.json  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @trial.errors, :status => :unprocessable_entity }
        format.json  { render :json => @trial.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /trials/1
  # DELETE /trials/1.xml
  # DELETE /trials/1.json
  def destroy
    @trial = Trial.find(params[:id])

    # Delete live trial instance if not nil
    unless @trial.instanceid.nil?
      # Populate username variable from trials model
      username = @trial.cloudaccount
      # Populate the apikey
      @cloud_account = CloudAccount.find_by_username(username)
      apikey = @cloud_account.apikey

      parameters = ["-u", username, "-a", apikey,
                    "-C", @trial.customername, "-E", @trial.customeremail]
      options = SnaplogicRackspace::ParseArguments.parse(parameters)
      @livetrial = SnaplogicRackspace::LiveTrialServer.new(options)
      @livetrial.deletelive(@trial.instanceid)
    end

    # Delete object  instance
    @trial.destroy

    respond_to do |format|
      format.html { redirect_to(trials_url) }
      format.xml  { head :ok }
      format.json  { head :ok }
    end
  end
end

app/helpers/trials_helper.rb
module TrialsHelper

  #helper_method :current_email

  private
    def current_email
      @current_email ||= Project.find(session[:customeremail])
    end

end

app/views/trials/_form.html.erb
<%= form_for(@trial) do |f| %>
  <% if @trial.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@trial.errors.count, "error") %> prohibited this trial from being saved:</h2>

      <ul>
      <% @trial.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Customer name" %><br />
    <%= f.text_field :customername %>
  </div>
  <div class="field">
    <%= f.label "Customer email"  %><br />
    <%= f.text_field :customeremail %>
  </div>
  <div class="field">
    <%= f.hidden_field :instancename %>
  </div>
  <div class="field">
    <%= f.hidden_field :instanceid %>
  </div>
  <div class="field">
    <%= f.hidden_field :imageid %>
  </div>
  <div class="field">
    <%= f.hidden_field :imageflavor %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/trials/edit.html.erb
<h1>Editing trial</h1>

<%= render 'form' %>

<%= link_to 'Show', @trial %> |
<%= link_to 'Back', trials_path %>

app/views/trials/index.html.erb
<img src="http://www.snaplogic.com/images/common/logo.png">
<br>
<h1>LiveTrials</h1>
Current User is: <%= current_user.username %> <%= link_to 'Logout', logout_path %>
<br><br>

<div class="digg_pagination">
    <div class="page_info">
      <%= page_entries_info @posts %>
    </div>
    <%= will_paginate @posts, :container => false %>
</div>

<br>

<table border="+1">
  <tr>
    <th>Customer Name</th>
    <th>Customer Email</th>
    <th>Instance Name</th>
    <th>IP address</th>
    <th>Cloud Account</th>
    <th>Expiration</th>
    <th>Status</th>
    <th colspan=3>Actions</th>
  </tr>

<% @trials.each do |trial| %>
  <tr>
    <td><%= trial.customername %></td>
    <td><%= trial.customeremail %></td>
    <td><%= trial.instancename %></td>
    <td align=center><%= trial.publicipaddr %></td>
    <td align=center><%= trial.cloudaccount %></td>
    <td align=center><% if trial.expired? %>
                     <font color="red">Expired</font>
                     <% else %>
                     <font color="green">Active</font>
                     <% end %> </td>
    <td align=center><%= trial.status %></td>
    <td><%= link_to 'Show', trial %></td>
    <td><%= link_to 'Destroy', trial, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>

</table>

<br />

<%= button_to 'Create New Trial', new_trial_path, :method => "get" %>

app/views/trials/new.html.erb
<img src="http://www.snaplogic.com/images/common/logo.png">
<br>
Current User is: <%= current_user.username %> <%= link_to 'Logout', logout_path %>
<br><br>

<h1>Create a New Trial</h1>

<%= render 'form' %>

<%= link_to 'Back', trials_path %>

app/views/trials/show.html.erb
<img src="http://www.snaplogic.com/images/common/logo.png">
<br>
Current User is: <%= current_user.username %> <%= link_to 'Logout', logout_path %>
<br><br>

<p id="notice"><%= notice %></p>

<p>
  <b>Customername:</b>
  <%= @trial.customername %>
</p>

<p>
  <b>Customeremail:</b>
  <%= @trial.customeremail %>
</p>

<p>
  <b>Instancename:</b>
  <%= @trial.instancename %>
</p>

<p>
  <b>Instanceid:</b>
  <%= @trial.instanceid %>
</p>

<p>
  <b>Imageid:</b>
  <%= @trial.imageid %>
</p>

<p>
  <b>Imageflavor:</b>
  <%= @trial.imageflavor %>
</p>

<p>
  <b>IP address:</b>
  <%= @trial.publicipaddr %>
</p>

<p>
  <b>Cloud Account</b>
  <%= @trial.cloudaccount %>
</p>

<p>
  <b>Trial Password</b>
  <%= @trial.trialpw %>
</p>

<p>
  <b>Rackspace Password</b>
  <%= @trial.instancepw %>
</p>

<p>
  <b>Status</b>
  <%= @trial.status %>
</p>

<%= link_to 'Back', trials_path %>